[build]
  # مجلد البناء
  publish = "dist/public"
  
  # أوامر البناء
  command = "npm run build:netlify"

[build.environment]
  # إعدادات Node.js
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  
  # متغيرات قاعدة البيانات
  DATABASE_URL = "postgresql://neondb_owner:npg_RjPm5AzCSe3X@ep-blue-bread-af97x8n0-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  
  # JWT Secrets
  JWT_ACCESS_SECRET = "xoOJpqGoJwriVTQtNE0hyR79OGncbx4gmbxrr1Iu9ztMdvzH4Am8qe032NlLUSgf"
  JWT_REFRESH_SECRET = "BeESfcZmlN9rwkT2Ill5QPBHKyp8hRYp09kl2Ag8yaiE8Pr4zuqZhuoHrXZXJKCc"
  
  # Frontend URL
  FRONTEND_URL = "https://globalpromonetwork.netlify.app"
  
  # Admin Configuration
  ADMIN_EMAIL = "1sanadsa1997@gmil.com"
  ADMIN_PASSWORD = "PromoHive@Admin2025!"
  
  # Platform Settings
  PLATFORM_NAME = "PromoHive"
  PLATFORM_URL = "https://globalpromonetwork.netlify.app"
  
  # CORS
  CORS_ORIGIN = "https://globalpromonetwork.netlify.app"
  
  # Environment
  NODE_ENV = "production"

# إعدادات Netlify Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# إعادة التوجيه للاختبار
[[redirects]]
  from = "/test-db"
  to = "/.netlify/functions/test-db"
  status = 200
  force = true

# إعادة التوجيه للـ API أولاً (أولوية عالية)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# إعادة التوجيه محددة للـ auth endpoints
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# إعادة التوجيه محددة للـ user endpoints
[[redirects]]
  from = "/api/user/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# إعادة التوجيه للـ SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# إعدادات الـ Headers للأمان
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

# إعدادات خاصة بالـ API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://globalpromonetwork.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"

# إعدادات خاصة بالصور والملفات الثابتة
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
