[build]
  # مجلد البناء
  publish = "dist/public"
  
  # أوامر البناء
  command = "npm run build:netlify"

[build.environment]
  # إعدادات Node.js
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# إعدادات Netlify Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "bcrypt"]

# إعادة التوجيه للـ SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# إعادة التوجيه للـ API Functions
[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/auth/me"
  to = "/.netlify/functions/auth"
  status = 200

# إعدادات الـ Headers للأمان
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

# إعدادات خاصة بالـ API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://globalpromonetwork.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"

# إعدادات خاصة بالصور والملفات الثابتة
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
